stages:
    - build
    - test
    - deploy

image: aboozar/laravel-docker:apiato-9

.init_ssh: &init_ssh |
    eval $(ssh-agent -s)
    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

  # Replace the last line with the following lines if you'd rather
  # leave StrictHostKeyChecking enabled (replace yourdomain.com):
  #
  #  ssh-keyscan yourdomain.com >> ~/.ssh/known_hosts
  #  chmod 644 ~/.ssh/known_hosts

.change_file_permissions: &change_file_permissions |
    find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
    find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

composer:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}-composer
        paths:
            - vendor/
    script:
        - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
        - cp .env.example .env
        - php artisan key:generate --no-interaction --quiet --force
    artifacts:
        expire_in: 1 month
        paths:
            - vendor/
            - .env

yarn:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}-yarn
        paths:
            - node_modules/
    script:
        - yarn install
        - yarn run production
    artifacts:
        expire_in: 1 month
        paths:
            - node_modules/
            - public/css/
            - public/js/

codestyle:
    stage: test
    dependencies: []
    script:
        - phpcs

phpunit:
    stage: test
    dependencies:
        - composer
    script:
        - php vendor/bin/phpunit --coverage-text --colors=never

staging:
    stage: deploy
    script:
        - *init_ssh
        - *change_file_permissions
        - php artisan deploy asanato.ir -s upload
    environment:
        name: staging
        url: https://api.asanato.ir
    only:
        - master

production:
    stage: deploy
    script:
        - *init_ssh
        - *change_file_permissions
        - php artisan deploy asanpay.com -s upload
    environment:
        name: production
        url: https://api.asanpay.com
    when: manual
    only:
        - master
