#!/bin/bash

php artisan clear-compiled
php artisan auth:clear-resets
php artisan cache:clear
php artisan config:clear
php artisan permission:cache-reset
php artisan route:clear
php artisan view:clear
php artisan event:clear
php artisan optimize:clear

composer dump
composer clear-cache
