<?php

namespace App\Containers\Transaction\Providers;

use App\Containers\Transaction\Models\Observers\TransactionObserver;
use App\Containers\Transaction\Models\Transaction;
use App\Ship\Parents\Providers\MainProvider;

/**
 * Class MainServiceProvider.
 *
 * The Main Service Provider of this container, it will be automatically registered in the framework.
 */
class MainServiceProvider extends MainProvider
{

    /**
     * Container Service Providers.
     *
     * @var array
     */
    public $serviceProviders = [
        // InternalServiceProviderExample::class,
    ];

    /**
     * Container Aliases
     *
     * @var array
     */
    public $aliases = [
        // 'Foo' => Bar::class,
    ];

    public function boot()
    {
        Transaction::observe(TransactionObserver::class);

        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * Register anything in the container.
     */
    public function register()
    {
        parent::register();

        // $this->app->bind(UserRepositoryInterface::class, UserRepository::class);
        // ...
    }
}
